server:
  port: 8092

eureka:
  instance:
    hostname: localhost
    port: 8091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

security:
    oauth2:
        client:
            access-token-validity-seconds: 1800
            authorized-grant-types: password,refresh_token
            client-id: tomwellAngularApp
            client-secret: $2a$10$OWdyA/qUvQ71CSbMMThAgep/z3piJgSpBaMBmZpa03YWvPqeyCVEi
            resource-ids: resources
            scope: read,write

spring:
    datasource:
        url: jdbc:h2:mem:test
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: none
        show-sql: true
