server:
  port: 8093

eureka:
  instance:
    hostname: localhost
    port: 8091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      password: '1234'
      platform: mysql
      url: jdbc:mysql://db4free.net:3306/tomwel
      username: root      
      hikari:
        maximum-pool-size: 30
        connectionTimeout: 30000
        idleTimeout: 600000
        maxLifetime: 1800000
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        generate-ddl: false
        hibernate:
            ddl-auto: create
        show-sql: true
        
    jackson:
      default-property-inclusion: NON_NULL

authserver:
  hostname: http://localhost:8092
security:
  oauth2:
    resource:
      userInfoUri: ${authserver.hostname}/user
